version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.geolocation
    environment:
      ADDONS: "eea.geolocation[test]"
      DEVELOP: "src/eea.geolocation"
